In [23]:
import torch.nn as nn

from utils.ftl_data_loader import FTLDataLoader

In [24]:
dt = FTLDataLoader("data/mini_nus_wide_train_guest.csv")

print(dt.data_matrix)

[2022-05-26 15:45:50] ftl_data_loader.py:57 INFO - mapping label value 0 to -1, 1 to +1


[[-0.041827  0.037656  0.830468 ...  0.003406  0.139864  0.346127]
 [-0.072071 -0.215349 -0.12748  ...  0.134116 -0.078017 -0.203804]
 [-0.046688  0.135819  0.185993 ... -0.313597  0.861375 -0.955271]
 ...
 [ 0.002206 -0.220415 -0.12001  ... -0.149214 -0.405655  0.134179]
 [ 0.272182 -0.089065 -0.080786 ... -0.280846  0.243175 -0.598673]
 [-0.097331 -0.224257 -0.128853 ...  0.563206  0.56376  -0.494249]]


In [25]:
print(dt.data_matrix)
print(type(dt.data_matrix))

[[-0.041827  0.037656  0.830468 ...  0.003406  0.139864  0.346127]
 [-0.072071 -0.215349 -0.12748  ...  0.134116 -0.078017 -0.203804]
 [-0.046688  0.135819  0.185993 ... -0.313597  0.861375 -0.955271]
 ...
 [ 0.002206 -0.220415 -0.12001  ... -0.149214 -0.405655  0.134179]
 [ 0.272182 -0.089065 -0.080786 ... -0.280846  0.243175 -0.598673]
 [-0.097331 -0.224257 -0.128853 ...  0.563206  0.56376  -0.494249]]
<class 'numpy.ndarray'>


In [2]:
from phe import paillier
import numpy as np

In [4]:
public_key, private_key = paillier.generate_paillier_keypair()
plain_list=[3,4,5]
print(plain_list)
encrypt_list=[public_key.encrypt(x) for x in plain_list]
print(encrypt_list)
encrypt_list=np.array(encrypt_list)
print(encrypt_list)

[3, 4, 5]
[<phe.paillier.EncryptedNumber object at 0x7ff5e41e8910>, <phe.paillier.EncryptedNumber object at 0x7ff5893fd340>, <phe.paillier.EncryptedNumber object at 0x7ff5e41e8a30>]


In [6]:
print(encrypt_list[0])

In [7]:
encrypt_list*=3
decrypt_list=[private_key.decrypt(x) for x in encrypt_list]
print(decrypt_list)

[9, 12, 15]


In [9]:
row=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
matrix=np.array([[1,2,3,4],[1,1,1,1],[2,2,2,2]])
print(row*matrix)

[[1 2 3 4]
 [2 2 2 2]
 [6 6 6 6]]


In [11]:
row=np.array([1,2,3])
print(row)
print(row.T)

[1 2 3]
[1 2 3]


In [22]:
new_row=np.expand_dims(row,axis=0)
print(new_row)

[[1 2 3]]


In [25]:
print(new_row.repeat(3,axis=0).T)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [24]:
print(new_row)

[[1 2 3]]
