In [5]:
import torch.nn as nn

from utils.ftl_data_loader import FTLDataLoader

In [6]:
dt = FTLDataLoader("data/mini_nus_wide_train_guest.csv")

print(dt.data_matrix)

[2022-05-25 19:52:04] ftl_data_loader.py:56 INFO - mapping label value 0 to -1, 1 to +1


[[-0.041827  0.037656  0.830468 ...  0.003406  0.139864  0.346127]
 [-0.072071 -0.215349 -0.12748  ...  0.134116 -0.078017 -0.203804]
 [-0.046688  0.135819  0.185993 ... -0.313597  0.861375 -0.955271]
 ...
 [ 0.002206 -0.220415 -0.12001  ... -0.149214 -0.405655  0.134179]
 [ 0.272182 -0.089065 -0.080786 ... -0.280846  0.243175 -0.598673]
 [-0.097331 -0.224257 -0.128853 ...  0.563206  0.56376  -0.494249]]


In [7]:
print(dt.data_matrix)
print(type(dt.data_matrix))

[[-0.041827  0.037656  0.830468 ...  0.003406  0.139864  0.346127]
 [-0.072071 -0.215349 -0.12748  ...  0.134116 -0.078017 -0.203804]
 [-0.046688  0.135819  0.185993 ... -0.313597  0.861375 -0.955271]
 ...
 [ 0.002206 -0.220415 -0.12001  ... -0.149214 -0.405655  0.134179]
 [ 0.272182 -0.089065 -0.080786 ... -0.280846  0.243175 -0.598673]
 [-0.097331 -0.224257 -0.128853 ...  0.563206  0.56376  -0.494249]]
<class 'numpy.ndarray'>


In [8]:
y=dt.data_matrix[0]
print(y)
print(len(y))

[-4.182700e-02  3.765600e-02  8.304680e-01  2.136790e-01 -3.387810e-01
  1.019740e-01 -1.041850e-01 -1.894880e-01 -1.984440e-01 -6.569690e-01
 -1.541440e-01  2.354200e-01  2.624260e-01  1.662290e-01 -3.545120e-01
  3.365400e-02  5.879100e-02 -2.722110e-01 -9.506200e-02  5.550700e-02
 -2.923020e-01  3.888200e-02  2.910600e-01 -4.537150e-01  3.779600e-02
  1.080530e-01  7.204300e-02 -2.666550e-01 -6.825200e-02  7.766600e-02
 -3.086940e-01  6.125900e-02  3.182200e-01 -4.290860e-01  2.327750e-01
 -1.500920e-01  5.670000e-02 -1.615550e-01 -3.128110e-01 -1.176400e-02
 -1.200530e-01  1.733760e-01  3.195960e-01 -4.933110e-01  1.501580e-01
 -2.484840e-01  1.032060e-01 -1.220880e-01  2.446900e-02 -3.989850e-01
 -2.169190e-01  2.145850e-01  2.080830e-01 -3.583770e-01  1.017000e-01
 -1.666290e-01 -2.410620e-01 -2.174440e-01 -9.039100e-02 -7.249780e-01
 -1.810880e-01  1.994820e-01  2.621480e-01 -3.551010e-01  4.335700e-02
  7.815600e-02 -2.467940e-01 -6.329300e-02 -1.468860e-01  8.507400e-02
 -2.56

In [15]:
model = nn.Sequential()
model.add_module("layer 1",nn.Linear(in_features=634,out_features=32,dtype=torch.float32))
# model.add_module("layer 1 activation",nn.Sigmoid())

In [12]:
out=model(torch.tensor(y,dtype=torch.float32))

In [14]:
print(out)
print(len(out))

tensor([0.4814, 0.4261, 0.4621, 0.5383, 0.5205, 0.5507, 0.4562, 0.4756, 0.4527,
        0.5699, 0.5592, 0.5479, 0.4877, 0.5218, 0.5013, 0.5485, 0.4855, 0.5035,
        0.5196, 0.4757, 0.5161, 0.4746, 0.4290, 0.5287, 0.5347, 0.4121, 0.4602,
        0.5216, 0.5147, 0.5733, 0.5378, 0.4913], grad_fn=<SigmoidBackward0>)
32


In [16]:
model = nn.Sequential()
model.add_module("layer 1",nn.Linear(in_features=634,out_features=32,dtype=torch.float32))
# model.add_module("layer 1 activation",nn.Sigmoid())

In [17]:
out=model(torch.tensor(y,dtype=torch.float32))
print(out)
print(len(out))

tensor([ 0.3174,  0.2573,  0.2001,  0.2104,  0.1491,  0.2742, -0.1522,  0.3750,
        -0.3093, -0.0495,  0.1455,  0.0136,  0.0608, -0.0341,  0.0972, -0.0113,
         0.2052,  0.1338, -0.0390, -0.1311, -0.1478,  0.0685, -0.1044, -0.2133,
         0.2327, -0.2503, -0.0035, -0.0706,  0.3198,  0.0988,  0.2309,  0.0808],
       grad_fn=<AddBackward0>)
32


In [19]:
tensors=torch.tensor(dt.data_matrix,dtype=torch.float32)

In [20]:
print(tensors)

tensor([[-0.0418,  0.0377,  0.8305,  ...,  0.0034,  0.1399,  0.3461],
        [-0.0721, -0.2153, -0.1275,  ...,  0.1341, -0.0780, -0.2038],
        [-0.0467,  0.1358,  0.1860,  ..., -0.3136,  0.8614, -0.9553],
        ...,
        [ 0.0022, -0.2204, -0.1200,  ..., -0.1492, -0.4057,  0.1342],
        [ 0.2722, -0.0891, -0.0808,  ..., -0.2808,  0.2432, -0.5987],
        [-0.0973, -0.2243, -0.1289,  ...,  0.5632,  0.5638, -0.4942]])


In [21]:
model = nn.Sequential()
model.add_module("layer 1",nn.Linear(in_features=634,out_features=32,dtype=torch.float32))
model.add_module("layer 1 activation",nn.Sigmoid())
outs=model(tensors)
print(outs)

tensor([[0.6207, 0.5464, 0.4837, 0.4784, 0.5271, 0.4710, 0.5397, 0.5185, 0.6477,
         0.4201, 0.5848, 0.4700, 0.4826, 0.4340, 0.5468, 0.4222, 0.4310, 0.4648,
         0.4592, 0.4400, 0.4062, 0.4840, 0.4870, 0.6160, 0.5484, 0.4565, 0.5208,
         0.4208, 0.5032, 0.5927, 0.5479, 0.5287],
        [0.4613, 0.5230, 0.5358, 0.4737, 0.5199, 0.5336, 0.4843, 0.5290, 0.5167,
         0.4984, 0.4702, 0.4993, 0.5584, 0.5385, 0.5244, 0.5718, 0.4961, 0.5059,
         0.4900, 0.5588, 0.4968, 0.5623, 0.4678, 0.4785, 0.4735, 0.5086, 0.5519,
         0.4643, 0.5335, 0.5121, 0.4931, 0.4913],
        [0.4470, 0.5165, 0.4759, 0.4706, 0.4673, 0.5351, 0.5484, 0.5798, 0.4792,
         0.4883, 0.4713, 0.5137, 0.4294, 0.4786, 0.5104, 0.4766, 0.4335, 0.5370,
         0.4039, 0.5283, 0.5536, 0.5590, 0.4881, 0.5690, 0.4955, 0.4496, 0.4933,
         0.5416, 0.4336, 0.5084, 0.4430, 0.5242],
        [0.5803, 0.5535, 0.5227, 0.5111, 0.5482, 0.5118, 0.5166, 0.4385, 0.5424,
         0.4188, 0.4476, 0.4702, 0.5101,

In [22]:
print(outs[0])

tensor([0.6207, 0.5464, 0.4837, 0.4784, 0.5271, 0.4710, 0.5397, 0.5185, 0.6477,
        0.4201, 0.5848, 0.4700, 0.4826, 0.4340, 0.5468, 0.4222, 0.4310, 0.4648,
        0.4592, 0.4400, 0.4062, 0.4840, 0.4870, 0.6160, 0.5484, 0.4565, 0.5208,
        0.4208, 0.5032, 0.5927, 0.5479, 0.5287], grad_fn=<SelectBackward0>)


In [23]:
y=dt.labels
print(y)

[ 1 -1  1  1 -1  1  1  1 -1  1  1 -1  1 -1  1  1 -1 -1 -1]


In [24]:
print(type(y))

<class 'numpy.ndarray'>


In [28]:
import numpy as np
np.dot(y,outs.detach().numpy())

array([1.81785682, 1.66926715, 1.46632695, 1.62892944, 1.44457519,
       1.41125774, 1.76030144, 1.20707241, 1.89512911, 1.37179124,
       1.52785546, 1.08930635, 1.39137992, 1.49156198, 1.5499925 ,
       1.15804708, 1.45555213, 1.165373  , 1.34882885, 1.37160242,
       1.61421636, 1.59274638, 1.55431834, 1.92141977, 1.50303733,
       1.31645605, 1.59025815, 1.66952842, 1.25275144, 1.76506597,
       1.60993922, 1.54380757])

In [29]:
model = nn.Sequential()
model.add_module("layer 1",nn.Linear(in_features=634,out_features=32,dtype=torch.float32))
model.add_module("layer 1 activation",nn.Sigmoid())
outs1=model(tensors[0:5])
outs2=model(tensors[5:9])
print(outs1)
print(outs2)

tensor([[0.5331, 0.4131, 0.4842, 0.4922, 0.4480, 0.5122, 0.5235, 0.4771, 0.5209,
         0.5281, 0.5350, 0.4777, 0.5115, 0.5011, 0.4891, 0.5058, 0.4827, 0.5885,
         0.4648, 0.5143, 0.5296, 0.4674, 0.5262, 0.6198, 0.4879, 0.5467, 0.4363,
         0.4125, 0.4672, 0.4550, 0.5230, 0.6268],
        [0.5230, 0.5304, 0.5803, 0.5269, 0.4930, 0.4536, 0.4809, 0.5073, 0.4940,
         0.5131, 0.5107, 0.5188, 0.4911, 0.4846, 0.4525, 0.4864, 0.5489, 0.5303,
         0.4991, 0.4890, 0.5365, 0.4875, 0.5283, 0.4749, 0.5192, 0.4710, 0.5846,
         0.5672, 0.5134, 0.6162, 0.5755, 0.5261],
        [0.4836, 0.4294, 0.4770, 0.4689, 0.4563, 0.4207, 0.4873, 0.5636, 0.5211,
         0.4805, 0.5083, 0.4517, 0.4649, 0.5048, 0.4604, 0.4950, 0.4927, 0.5607,
         0.5137, 0.4450, 0.4828, 0.4798, 0.5425, 0.4960, 0.4368, 0.4817, 0.4866,
         0.4046, 0.4675, 0.4700, 0.4660, 0.4562],
        [0.4671, 0.4894, 0.4680, 0.5388, 0.5121, 0.6052, 0.5223, 0.5727, 0.4923,
         0.4126, 0.5007, 0.5534, 0.6016,

In [32]:
outs=[]
outs+=outs1
outs+=outs2
print(outs[[1,2,3,4]])

TypeError: list indices must be integers or slices, not list